# Generated by Django 5.0.6 on 2024-06-12 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantsEn',
            fields=[
                ('plant_name_en', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('plant_audio_en', models.BinaryField()),
                ('plant_text_en', models.TextField()),
                ('plant_description_en', models.TextField()),
            ],
            options={
                'verbose_name': 'Plant English',
                'verbose_name_plural': 'Plants English',
                'db_table': 'plants_en',
            },
        ),
        migrations.CreateModel(
            name='PlantsHy',
            fields=[
                ('plant_name_hy', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('plant_audio_hy', models.BinaryField()),
                ('plant_text_hy', models.TextField()),
                ('plant_description_hy', models.TextField()),
            ],
            options={
                'verbose_name': 'Plant Armenian',
                'verbose_name_plural': 'Plants Armenian',
                'db_table': 'plants_hy',
            },
        ),
        migrations.CreateModel(
            name='PlantsAll',
            fields=[
                ('plant_name_latin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('plant_family', models.CharField(max_length=255)),
                ('plant_genus', models.CharField(max_length=255)),
                ('plant_order', models.CharField(max_length=255)),
                ('plant_image', models.ImageField(upload_to='')),
                ('plant_video', models.BinaryField()),
                ('plant_name_en', models.ForeignKey(db_column='plant_name_en', on_delete=django.db.models.deletion.CASCADE, to='plantparse.plantsen')),
                ('plant_name_hy', models.ForeignKey(db_column='plant_name_hy', on_delete=django.db.models.deletion.CASCADE, to='plantparse.plantshy')),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'plants_all',
            },
        ),
    ]
